husky:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  bl_knee_position_controller:
    type: effort_controllers/JointPositionController
    joint: bl_knee
    pid: {p: 0.0, i: 0.0, d: 0.0}